/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Flags {
    'useCustomTechs'?: boolean;
    'useCustomTeams'?: boolean;
    'fixedPlayerParametersForCustomTeams'?: boolean;
    'unexploredAreasPartiallyVisible'?: boolean;
    'nonDefaultTilesetMapSizeLargeNeverBeenReducedToMedium'?: boolean;
    'melee'?: boolean;
    'changeAllyPriorities'?: boolean;
    'hideMinimapOnPreviewScreens'?: boolean;
    'useItemClassificationSystem'?: boolean;
    'tftRequired'?: boolean;
    'useTerrainFog'?: boolean;
    'showWaterWavesOnRollingShores'?: boolean;
    'showWaterWavesOnCliffShores'?: boolean;
    'mapPropertiesMenuOpenedAtLeastOnce'?: boolean;
    'useCustomUpgrades'?: boolean;
    'useCustomAbilities'?: boolean;
    'customWaterTintColor'?: boolean;
    'flag17'?: boolean;
    'flag18'?: boolean;
    'flag19'?: boolean;
    'flag20'?: boolean;
    'useCustomAbilitySkin'?: boolean;
    'useAccurateProbabilitiesForCalculation'?: boolean;
    'rest'?: Array<boolean>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "useCustomTechs",
            "baseName": "useCustomTechs",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useCustomTeams",
            "baseName": "useCustomTeams",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "fixedPlayerParametersForCustomTeams",
            "baseName": "fixedPlayerParametersForCustomTeams",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "unexploredAreasPartiallyVisible",
            "baseName": "unexploredAreasPartiallyVisible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "nonDefaultTilesetMapSizeLargeNeverBeenReducedToMedium",
            "baseName": "nonDefaultTilesetMapSizeLargeNeverBeenReducedToMedium",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "melee",
            "baseName": "melee",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "changeAllyPriorities",
            "baseName": "changeAllyPriorities",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hideMinimapOnPreviewScreens",
            "baseName": "hideMinimapOnPreviewScreens",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useItemClassificationSystem",
            "baseName": "useItemClassificationSystem",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tftRequired",
            "baseName": "tftRequired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useTerrainFog",
            "baseName": "useTerrainFog",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "showWaterWavesOnRollingShores",
            "baseName": "showWaterWavesOnRollingShores",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "showWaterWavesOnCliffShores",
            "baseName": "showWaterWavesOnCliffShores",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mapPropertiesMenuOpenedAtLeastOnce",
            "baseName": "mapPropertiesMenuOpenedAtLeastOnce",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useCustomUpgrades",
            "baseName": "useCustomUpgrades",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useCustomAbilities",
            "baseName": "useCustomAbilities",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customWaterTintColor",
            "baseName": "customWaterTintColor",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "flag17",
            "baseName": "flag17",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "flag18",
            "baseName": "flag18",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "flag19",
            "baseName": "flag19",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "flag20",
            "baseName": "flag20",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useCustomAbilitySkin",
            "baseName": "useCustomAbilitySkin",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "useAccurateProbabilitiesForCalculation",
            "baseName": "useAccurateProbabilitiesForCalculation",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rest",
            "baseName": "rest",
            "type": "Array<boolean>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Flags.attributeTypeMap;
    }

    public constructor() {
    }
}

