/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { W3str } from '../models/W3str';
import { HttpFile } from '../http/http';

export class PrologueScreen {
    'prologueScreenPath'?: W3str;
    'prologueScreenText'?: W3str;
    'prologueScreenTitle'?: W3str;
    'prologueScreenSubtitle'?: W3str;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "prologueScreenPath",
            "baseName": "prologueScreenPath",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "prologueScreenText",
            "baseName": "prologueScreenText",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "prologueScreenTitle",
            "baseName": "prologueScreenTitle",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "prologueScreenSubtitle",
            "baseName": "prologueScreenSubtitle",
            "type": "W3str",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PrologueScreen.attributeTypeMap;
    }

    public constructor() {
    }
}

