/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RandomUnitTable } from '../models/RandomUnitTable';
import { HttpFile } from '../http/http';

export class RandomUnitTablesChunk {
    'numTable'?: number;
    'table'?: Array<RandomUnitTable>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numTable",
            "baseName": "numTable",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "Array<RandomUnitTable>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RandomUnitTablesChunk.attributeTypeMap;
    }

    public constructor() {
    }
}

