/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RandomItemTable } from '../models/RandomItemTable';
import { HttpFile } from '../http/http';

export class RandomItemTablesChunk {
    'numTable'?: number;
    'table'?: Array<RandomItemTable>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numTable",
            "baseName": "numTable",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "table",
            "baseName": "table",
            "type": "Array<RandomItemTable>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RandomItemTablesChunk.attributeTypeMap;
    }

    public constructor() {
    }
}

