/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RandomUnitTableRow } from '../models/RandomUnitTableRow';
import { W3str } from '../models/W3str';
import { HttpFile } from '../http/http';

export class RandomUnitTable {
    'num'?: number;
    'name'?: W3str;
    'numColumnType'?: number;
    'columnType'?: Array<number>;
    'numRow'?: number;
    'row'?: Array<RandomUnitTableRow>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "num",
            "baseName": "num",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "numColumnType",
            "baseName": "numColumnType",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "columnType",
            "baseName": "columnType",
            "type": "Array<number>",
            "format": "int64"
        },
        {
            "name": "numRow",
            "baseName": "numRow",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "row",
            "baseName": "row",
            "type": "Array<RandomUnitTableRow>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RandomUnitTable.attributeTypeMap;
    }

    public constructor() {
    }
}

