/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemSet } from '../models/ItemSet';
import { W3str } from '../models/W3str';
import { HttpFile } from '../http/http';

export class RandomItemTable {
    'num'?: number;
    'name'?: W3str;
    'numSet'?: number;
    'set'?: Array<ItemSet>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "num",
            "baseName": "num",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "numSet",
            "baseName": "numSet",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "set",
            "baseName": "set",
            "type": "Array<ItemSet>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RandomItemTable.attributeTypeMap;
    }

    public constructor() {
    }
}

