/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tech } from '../models/Tech';
import { HttpFile } from '../http/http';

export class TechsChunk {
    'numTech'?: number;
    'tech'?: Array<Tech>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numTech",
            "baseName": "numTech",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "tech",
            "baseName": "tech",
            "type": "Array<Tech>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TechsChunk.attributeTypeMap;
    }

    public constructor() {
    }
}

