/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UnknownV0ToV3 {
    'unknownV0Int1'?: number;
    'unknownV0Int2'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "unknownV0Int1",
            "baseName": "unknownV0Int1",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "unknownV0Int2",
            "baseName": "unknownV0Int2",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return UnknownV0ToV3.attributeTypeMap;
    }

    public constructor() {
    }
}

