/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UnknownV4ToV8 {
    'unknownV4Int1'?: number;
    'unknownV4Int2'?: number;
    'unknownV4Int3'?: number;
    'unknownV4Float1'?: number;
    'unknownV4Float2'?: number;
    'unknownV4Float3'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "unknownV4Int1",
            "baseName": "unknownV4Int1",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "unknownV4Int2",
            "baseName": "unknownV4Int2",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "unknownV4Int3",
            "baseName": "unknownV4Int3",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "unknownV4Float1",
            "baseName": "unknownV4Float1",
            "type": "number",
            "format": "float"
        },
        {
            "name": "unknownV4Float2",
            "baseName": "unknownV4Float2",
            "type": "number",
            "format": "float"
        },
        {
            "name": "unknownV4Float3",
            "baseName": "unknownV4Float3",
            "type": "number",
            "format": "float"
        }    ];

    static getAttributeTypeMap() {
        return UnknownV4ToV8.attributeTypeMap;
    }

    public constructor() {
    }
}

