/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Upgrade } from '../models/Upgrade';
import { HttpFile } from '../http/http';

export class UpgradesChunk {
    'numUpgrade'?: number;
    'upgrade'?: Array<Upgrade>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "numUpgrade",
            "baseName": "numUpgrade",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "upgrade",
            "baseName": "upgrade",
            "type": "Array<Upgrade>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UpgradesChunk.attributeTypeMap;
    }

    public constructor() {
    }
}

