/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { W3id } from '../models/W3id';
import { HttpFile } from '../http/http';

export class Upgrade {
    'players'?: number;
    'id'?: W3id;
    'level'?: number;
    'availability'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "players",
            "baseName": "players",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "W3id",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "availability",
            "baseName": "availability",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return Upgrade.attributeTypeMap;
    }

    public constructor() {
    }
}

