/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CameraBounds } from '../models/CameraBounds';
import { Flags } from '../models/Flags';
import { Fog } from '../models/Fog';
import { ForcesChunk } from '../models/ForcesChunk';
import { GameVersion } from '../models/GameVersion';
import { GraphicsModes } from '../models/GraphicsModes';
import { LoadingScreen } from '../models/LoadingScreen';
import { Margins } from '../models/Margins';
import { PlayersChunk } from '../models/PlayersChunk';
import { PrologueScreen } from '../models/PrologueScreen';
import { RandomItemTablesChunk } from '../models/RandomItemTablesChunk';
import { RandomUnitTablesChunk } from '../models/RandomUnitTablesChunk';
import { TechsChunk } from '../models/TechsChunk';
import { UnknownV0ToV3 } from '../models/UnknownV0ToV3';
import { UnknownV4ToV8 } from '../models/UnknownV4ToV8';
import { UpgradesChunk } from '../models/UpgradesChunk';
import { W3char } from '../models/W3char';
import { W3id } from '../models/W3id';
import { W3str } from '../models/W3str';
import { WaterColor } from '../models/WaterColor';
import { HttpFile } from '../http/http';

export class W3W3i {
    'mapName'?: string;
    'version'?: number;
    'saves'?: number;
    'editorVersion'?: number;
    'gameVersion'?: GameVersion;
    'mapNameRaw'?: W3str;
    'author'?: W3str;
    'recommendedPlayers'?: W3str;
    'unknownV0ToV3'?: UnknownV0ToV3;
    'unknownV4ToV8'?: UnknownV4ToV8;
    'unknownString'?: W3str;
    'cameraBounds'?: CameraBounds;
    'margins'?: Margins;
    'mapWidth'?: number;
    'mapHeight'?: number;
    'unknownV3Int1'?: number;
    'flags'?: Flags;
    'tileset'?: W3W3iTilesetEnum;
    'loadingScreen'?: LoadingScreen;
    'gameDataSet'?: W3W3iGameDataSetEnum;
    'unknownPath'?: W3str;
    'prologueScreen'?: PrologueScreen;
    'fog'?: Fog;
    'globalWeatherId'?: W3id;
    'soundEnvironment'?: W3str;
    'lightEnvironment'?: W3char;
    'waterColor'?: WaterColor;
    'scriptLanguage'?: W3W3iScriptLanguageEnum;
    'supportedGraphicsModes'?: GraphicsModes;
    'gameDataVersion'?: W3W3iGameDataVersionEnum;
    'playersChunk'?: PlayersChunk;
    'forcesChunk'?: ForcesChunk;
    'upgradesChunk'?: UpgradesChunk;
    'techsChunk'?: TechsChunk;
    'randomUnitTablesChunk'?: RandomUnitTablesChunk;
    'randomItemTablesChunk'?: RandomItemTablesChunk;
    'scriptLanguage2'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mapName",
            "baseName": "mapName",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "saves",
            "baseName": "saves",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "editorVersion",
            "baseName": "editorVersion",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "gameVersion",
            "baseName": "gameVersion",
            "type": "GameVersion",
            "format": ""
        },
        {
            "name": "mapNameRaw",
            "baseName": "mapNameRaw",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "recommendedPlayers",
            "baseName": "recommendedPlayers",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "unknownV0ToV3",
            "baseName": "unknownV0ToV3",
            "type": "UnknownV0ToV3",
            "format": ""
        },
        {
            "name": "unknownV4ToV8",
            "baseName": "unknownV4ToV8",
            "type": "UnknownV4ToV8",
            "format": ""
        },
        {
            "name": "unknownString",
            "baseName": "unknownString",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "cameraBounds",
            "baseName": "cameraBounds",
            "type": "CameraBounds",
            "format": ""
        },
        {
            "name": "margins",
            "baseName": "margins",
            "type": "Margins",
            "format": ""
        },
        {
            "name": "mapWidth",
            "baseName": "mapWidth",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "mapHeight",
            "baseName": "mapHeight",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "unknownV3Int1",
            "baseName": "unknownV3Int1",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "flags",
            "baseName": "flags",
            "type": "Flags",
            "format": ""
        },
        {
            "name": "tileset",
            "baseName": "tileset",
            "type": "W3W3iTilesetEnum",
            "format": ""
        },
        {
            "name": "loadingScreen",
            "baseName": "loadingScreen",
            "type": "LoadingScreen",
            "format": ""
        },
        {
            "name": "gameDataSet",
            "baseName": "gameDataSet",
            "type": "W3W3iGameDataSetEnum",
            "format": ""
        },
        {
            "name": "unknownPath",
            "baseName": "unknownPath",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "prologueScreen",
            "baseName": "prologueScreen",
            "type": "PrologueScreen",
            "format": ""
        },
        {
            "name": "fog",
            "baseName": "fog",
            "type": "Fog",
            "format": ""
        },
        {
            "name": "globalWeatherId",
            "baseName": "globalWeatherId",
            "type": "W3id",
            "format": ""
        },
        {
            "name": "soundEnvironment",
            "baseName": "soundEnvironment",
            "type": "W3str",
            "format": ""
        },
        {
            "name": "lightEnvironment",
            "baseName": "lightEnvironment",
            "type": "W3char",
            "format": ""
        },
        {
            "name": "waterColor",
            "baseName": "waterColor",
            "type": "WaterColor",
            "format": ""
        },
        {
            "name": "scriptLanguage",
            "baseName": "scriptLanguage",
            "type": "W3W3iScriptLanguageEnum",
            "format": ""
        },
        {
            "name": "supportedGraphicsModes",
            "baseName": "supportedGraphicsModes",
            "type": "GraphicsModes",
            "format": ""
        },
        {
            "name": "gameDataVersion",
            "baseName": "gameDataVersion",
            "type": "W3W3iGameDataVersionEnum",
            "format": ""
        },
        {
            "name": "playersChunk",
            "baseName": "playersChunk",
            "type": "PlayersChunk",
            "format": ""
        },
        {
            "name": "forcesChunk",
            "baseName": "forcesChunk",
            "type": "ForcesChunk",
            "format": ""
        },
        {
            "name": "upgradesChunk",
            "baseName": "upgradesChunk",
            "type": "UpgradesChunk",
            "format": ""
        },
        {
            "name": "techsChunk",
            "baseName": "techsChunk",
            "type": "TechsChunk",
            "format": ""
        },
        {
            "name": "randomUnitTablesChunk",
            "baseName": "randomUnitTablesChunk",
            "type": "RandomUnitTablesChunk",
            "format": ""
        },
        {
            "name": "randomItemTablesChunk",
            "baseName": "randomItemTablesChunk",
            "type": "RandomItemTablesChunk",
            "format": ""
        },
        {
            "name": "scriptLanguage2",
            "baseName": "scriptLanguage2",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return W3W3i.attributeTypeMap;
    }

    public constructor() {
    }
}


export type W3W3iTilesetEnum = "ASHENVALE" | "BARRENS" | "FELWOOD" | "DUNGEON" | "LORDAERON_FALL" | "UNDERGROUND" | "ICECROWN" | "DALARAN_RUINS" | "BLACK_CITADEL" | "LORDAERON_SUMMER" | "NORTHREND" | "OUTLAND" | "VILLAGE_FALL" | "VILLAGE" | "LORDAERON_WINTER" | "DALARAN" | "CITYSCAPE" | "SUNKEN_RUINS" ;
export type W3W3iGameDataSetEnum = "DEFAULT" | "CUSTOM" | "MELEE" ;
export type W3W3iScriptLanguageEnum = "JASS" | "LUA" ;
export type W3W3iGameDataVersionEnum = "ROC" | "TFT" ;

