/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WaterColor {
    'red'?: number;
    'green'?: number;
    'blue'?: number;
    'alpha'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "red",
            "baseName": "red",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "green",
            "baseName": "green",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "blue",
            "baseName": "blue",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "alpha",
            "baseName": "alpha",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return WaterColor.attributeTypeMap;
    }

    public constructor() {
    }
}

